/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_codextropy_mycryptoapp_MainActivity.h"
/* Header for class com_codextropy_mycryptoapp_MainActivity */

JNIEXPORT jstring JNICALL Java_com_codextropy_mycryptoapp_MainActivity_CallNative
  (JNIEnv *env, jobject object)
{
  return env->NewStringUTF("Test");
}
