/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codextropy_mycryptoapp_MainActivity */

#ifndef _Included_com_codextropy_mycryptoapp_MainActivity
#define _Included_com_codextropy_mycryptoapp_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codextropy_mycryptoapp_MainActivity
 * Method:    CallNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_codextropy_mycryptoapp_MainActivity_CallNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
